---
- name: Install unattended-upgrades
  apt:
    name: unattended-upgrades
    state: present

- name: Configure unattended upgrades file
  copy:
    src: 50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades

- name: Configure auto upgrades file
  copy:
    src: 20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
