---
- name: Ensure use of ssh protocol 2
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: "^Protocol"
    line: "Protocol 2"
  notify: restart sshd

- name: Disallow password authentication for ssh
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
  notify: restart sshd

- name: Disallow challenge response authentication for ssh
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: "^ChallengeResponseAuthentication"
    line: "ChallengeResponseAuthentication no"
  notify: restart sshd

- name: Disallow root login through ssh
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
  notify: restart sshd

- name: Enable public key authentication for ssh
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: "^PubkeyAuthentication"
    line: "PubkeyAuthentication yes"
  notify: restart sshd

- name: Ensure there is an 'ssh-user' group
  group:
    name: ssh-user
    state: present

- name: Ensure the admin user is in the 'ssh-user' group
  user:
    name: "{{ admin_username }}"
    groups: ssh-user
    append: yes

- name: Restrict ssh access to users in the 'ssh-user' group
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: "^AllowGroups"
    line: "AllowGroups ssh-user"
  notify: restart sshd
