---
- name: Install ufw
  apt:
    name: ufw
    state: present

- name: By default, deny all incoming traffic
  ufw:
    policy: deny
    direction: incoming

- name: By default, allow all outgoing traffic
  ufw:
    policy: allow
    direction: outgoing

- name: Setup ufw rule to allow ssh
  ufw:
    rule: allow
    port: 22
    proto: tcp

- name: Enable ufw with logging
  ufw:
    logging: on
    state: enabled

