---
- name: Install postgresql
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql-9.5
    - postgresql-contrib-9.5
    - postgresql-server-dev-9.5
    - python-psycopg2

- name: Add the huginn postgresql role
  postgresql_user:
    name: "{{ huginn_pg_role_name }}"
    password: "{{ huginn_pg_role_password }}"
    role_attr_flags: LOGIN,CREATEDB,NOSUPERUSER
    state: present
  become: yes
  become_user: postgres

- name: Create the huginn database
  postgresql_db:
    name: "{{ huginn_pg_db_name }}"
    owner: "{{ huginn_pg_role_name }}"
    state: present
  become: yes
  become_user: postgres

- name: Ensure the role has access to the database
  postgresql_user:
    name: "{{ huginn_pg_role_name }}"
    db: "{{ huginn_pg_db_name }}"
    priv: ALL
    state: present
  become: yes
  become_user: postgres

- name: Schedule regular database dumps
  cron:
    name: huginn gzipped database dump.
    job: "pg_dump {{ huginn_pg_db_name }} | gzip > /home/{{ huginn_username}}/{{ huginn_pg_db_name }}_db_dump.gz"
    special_time: daily
    state: present
  become: yes
  become_user: "{{ huginn_username }}"
