---
- name: Add the certbot repo
  apt_repository:
    repo: "ppa:certbot/certbot"
    state: present

- name: Install certbot and the nginx plugin
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - certbot
    - python-certbot-nginx

- name: Check if a letsencrypt certificate already exists.
  stat:
    path: /etc/letsencrypt/live/{{ huginn_domain }}/cert.pem
  register: huginn_cert

- name: Generate a new certificate through letsencrypt
  command: "certbot certonly --nginx --noninteractive --agree-tos --email {{ huginn_cert_email }} -d {{ huginn_domain }}"
  when: not huginn_cert.stat.exists

- name: Enable nginx's ssl setting
  lineinfile:
    path: /etc/nginx/sites-enabled/huginn
    regexp: "^  # ssl on;"
    line: "  ssl on;"
    state: present
  notify: restart nginx



