---
- name: Add the certbot repo
  apt_repository:
    repo: "ppa:certbot/certbot"
    state: present

- name: Install nginx, certbot, and the nginx plugin
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - nginx
    - certbot
    - python-certbot-nginx

- name: Open port 80
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Open port 443
  ufw:
    rule: allow
    port: 443
    proto: tcp

- name: Check if a letsencrypt certificate already exists.
  stat:
    path: /etc/letsencrypt/live/{{ huginn_domain }}/cert.pem
  register: huginn_cert

- name: Get a default nginx config in place for letsencrypt
  template:
    src: nginx_default.jinja2
    dest: "/etc/nginx/sites-enabled/default"
  when: not huginn_cert.stat.exists

- name: Restart nginx
  service:
    name: nginx
    state: restarted
  when: not huginn_cert.stat.exists

- name: Generate a new certificate through letsencrypt
  command: "certbot certonly --nginx --noninteractive --agree-tos --email {{ huginn_cert_email }} -d {{ huginn_domain }}"
  when: not huginn_cert.stat.exists

- name: Schedule certificate auto-renewal
  cron:
    name: huginn certificate auto-renewal.
    job: "certbot renew --quiet --no-self-upgrade"
    special_time: daily
    state: present

- name: Remove the default nginx config
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify: restart nginx

- name: Create the huginn nginx config
  template: 
    src: nginx.jinja2
    dest: "/etc/nginx/sites-available/huginn"
  notify: restart nginx

- name: Link the huginn nginx config into sites-enabled
  file:
    src: "/etc/nginx/sites-available/huginn"
    dest: "/etc/nginx/sites-enabled/huginn"
    state: link
  notify: restart nginx
