---
- name: "Install Ruby 2.3"
  apt:
    name: ruby2.3
    state: present

- name: Install native extensions and build tools needed for ruby gems
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    # These 5 are required to build nokogiri
    - build-essential
    - patch
    - ruby-dev
    - zlib1g-dev
    - liblzma-dev
    # Required for rails
    - curl
    - libcurl4-openssl-dev
    # Needed for init files
    - runit
    # Needed for huginn's graph visualizations
    - graphviz

- name: Install bundler, foreman, and rake gems
  gem:
    name: "{{ item }}"
    include_doc: no
    user_install: no
    state: present
  with_items:
    - bundler
    - foreman
    - rake

